# **It is use for classification**

In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.naive_bayes import GaussianNB as GNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score,roc_auc_score, roc_curve, auc, mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder, Normalizer, Binarizer,OrdinalEncoder,RobustScaler
from sklearn.model_selection import cross_val_score
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# **Gaussian Naive Bayes**

In [22]:
X=df.drop('species',axis=1)
y=df['species']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
Gausan=GNB()
Gausian.fit(X_train,y_train)
y_pred=Gausian.predict(X_test)

print('Accuracy:',accuracy_score(y_test,y_pred))
print('Precision:',precision_score(y_test,y_pred,average='macro'))
print('Recall:',recall_score(y_test,y_pred,average='macro'))
print('F1:',f1_score(y_test,y_pred,average='macro'))
print('Confusion Matrix:',confusion_matrix(y_test,y_pred))
print('Classification Report:',classification_report(y_test,y_pred))
y_pred_prob = Gausian.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_pred_prob, multi_class='ovr')
print("ROC AUC Score (OVR):", roc_auc)
scores = cross_val_score(Gausian, X, y, cv=5, scoring='accuracy')
print("Cross-Validation Accuracy Scores:", scores)
print("Mean CV Accuracy:", scores.mean())

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0
Confusion Matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

ROC AUC Score (OVR): 1.0
Cross-Validation Accuracy Scores: [0.93333333 0.96666667 0.93333333 0.93333333 1.        ]
Mean CV Accuracy: 0.9533333333333334


# **Multinomial Naive Bayes**

In [23]:
df=sns.load_dataset('iris')

X=df.drop('species',axis=1)
y=df['species']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
Multinomial=MultinomialNB()
Multinomial.fit(X_train,y_train)
y_pred=Multinomial.predict(X_test)

print('Accuracy:',accuracy_score(y_test,y_pred))
print('Precision:',precision_score(y_test,y_pred,average='macro'))
print('Recall:',recall_score(y_test,y_pred,average='macro'))
print('F1:',f1_score(y_test,y_pred,average='macro'))
print('Confusion Matrix:',confusion_matrix(y_test,y_pred))
print('Classification Report:',classification_report(y_test,y_pred))
y_pred_prob = Gausian.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_pred_prob, multi_class='ovr')
print("ROC AUC Score (OVR):", roc_auc)
scores = cross_val_score(Gausian, X, y, cv=5, scoring='accuracy')
print("Cross-Validation Accuracy Scores:", scores)
print("Mean CV Accuracy:", scores.mean())

Accuracy: 0.9
Precision: 0.9166666666666666
Recall: 0.9090909090909092
F1: 0.899749373433584
Confusion Matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
Classification Report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.75      1.00      0.86         9
   virginica       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30

ROC AUC Score (OVR): 1.0
Cross-Validation Accuracy Scores: [0.93333333 0.96666667 0.93333333 0.93333333 1.        ]
Mean CV Accuracy: 0.9533333333333334


# **Bernoulli Naive Bayes it works with 0s and 1s**

In [24]:
df=sns.load_dataset('iris')

X=df.drop('species',axis=1)
y=df['species']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
bernoulli=BernoulliNB()
bernoulli.fit(X_train,y_train)
y_pred=bernoulli.predict(X_test)

print('Accuracy:',accuracy_score(y_test,y_pred))
print('Precision:',precision_score(y_test,y_pred,average='macro'))
print('Recall:',recall_score(y_test,y_pred,average='macro'))
print('F1:',f1_score(y_test,y_pred,average='macro'))
print('Confusion Matrix:',confusion_matrix(y_test,y_pred))
print('Classification Report:',classification_report(y_test,y_pred))
y_pred_prob = Gausian.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_pred_prob, multi_class='ovr')
print("ROC AUC Score (OVR):", roc_auc)
scores = cross_val_score(Gausian, X, y, cv=5, scoring='accuracy')
print("Cross-Validation Accuracy Scores:", scores)
print("Mean CV Accuracy:", scores.mean())

Accuracy: 0.3
Precision: 0.09999999999999999
Recall: 0.3333333333333333
F1: 0.15384615384615385
Confusion Matrix: [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
Classification Report:               precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        10
  versicolor       0.30      1.00      0.46         9
   virginica       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30

ROC AUC Score (OVR): 1.0
Cross-Validation Accuracy Scores: [0.93333333 0.96666667 0.93333333 0.93333333 1.        ]
Mean CV Accuracy: 0.9533333333333334
